'''
Module containing the exception: ArgumentError
'''

from . import base

class ArgumentError(base.BaseException):
    '''
    Exception raised when an argument is invalid
    '''

    pass
