'''
Module containing the exception: ConnectionError
'''

from . import base

class ConnectionError(base.BaseException):
    '''
    Exception raised when a connection to a server fails
    '''

    pass
